// <auto-generated />
using System;
using FirstWebApp.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250416202303_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirstWebApp.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BaseSalary")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Departament")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MonthlyBonus")
                        .HasPrecision(16, 2)
                        .HasColumnType("float(16)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a7e7dcc7-9e08-41e5-8de2-cec69e2018a7"),
                            BaseSalary = 5000,
                            CreatedAtUtc = new DateTime(2025, 4, 16, 20, 23, 2, 582, DateTimeKind.Utc).AddTicks(7792),
                            Departament = "IT",
                            MonthlyBonus = 100.0,
                            Name = "Jan",
                            Surname = "Kowalski"
                        },
                        new
                        {
                            Id = new Guid("2f4b52f8-0823-42d9-97a2-28839865a3cd"),
                            BaseSalary = 3000,
                            CreatedAtUtc = new DateTime(2025, 4, 16, 20, 23, 2, 582, DateTimeKind.Utc).AddTicks(7795),
                            Departament = "Maintenance",
                            MonthlyBonus = 150.0,
                            Name = "Andrzej",
                            Surname = "Kowalski"
                        },
                        new
                        {
                            Id = new Guid("16fa4b45-518f-4da5-91f3-6b9b1a524ca3"),
                            BaseSalary = 4000,
                            CreatedAtUtc = new DateTime(2025, 4, 16, 20, 23, 2, 582, DateTimeKind.Utc).AddTicks(7797),
                            Departament = "Engineering",
                            MonthlyBonus = 120.0,
                            Name = "Paweł",
                            Surname = "Janusz"
                        },
                        new
                        {
                            Id = new Guid("81a30b7a-4463-4cab-ac5e-fa987a9c1dff"),
                            BaseSalary = 4500,
                            CreatedAtUtc = new DateTime(2025, 4, 16, 20, 23, 2, 582, DateTimeKind.Utc).AddTicks(7798),
                            Departament = "HR",
                            MonthlyBonus = 50.0,
                            Name = "Joanna",
                            Surname = "Niewiadoma"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
